clc;
clear;
close all;
load('breast_cancer_data.mat');
[r_data,c_data] = size(breast_cancer_data);
labels = breast_cancer_data(:,c_data);
features = breast_cancer_data(:,1:c_data-1);
sum_feature = sum(features,2);
features = features ./ repmat(sum_feature,1,c_data-1);
libsvmwrite('breast_cancer_data_multi',labels,features);